(function(){var h={},mt={},c={id:"447fc101c0babe006f245f649af01989",dm:["redwind.cn"],js:"tongji.baidu.com/hm-web/js/",etrk:[],icon:'&#32593;&#31449;&#32479;&#35745;|txt|0|0',ctrk:true,align:1,nv:-1,vdur:1800000,age:31536000000,rec:0,rp:[],trust:1,vcard:1289525,qiao:0,lxb:1289525,conv:0,med:0,cvcc:'',cvcf:[],apps:''};var q=void 0,r=!0,s=null,w=!1;mt.j={};mt.j.N=/msie (\d+\.\d+)/i.test(navigator.userAgent);mt.j.La=/msie (\d+\.\d+)/i.test(navigator.userAgent)?document.documentMode||+RegExp.$1:q;mt.j.cookieEnabled=navigator.cookieEnabled;mt.j.javaEnabled=navigator.javaEnabled();mt.j.language=navigator.language||navigator.browserLanguage||navigator.systemLanguage||navigator.userLanguage||"";mt.j.Qa=(window.screen.width||0)+"x"+(window.screen.height||0);mt.j.colorDepth=window.screen.colorDepth||0;mt.cookie={};
mt.cookie.set=function(a,e,f){var d;f.K&&(d=new Date,d.setTime(d.getTime()+f.K));document.cookie=a+"="+e+(f.domain?"; domain="+f.domain:"")+(f.path?"; path="+f.path:"")+(d?"; expires="+d.toGMTString():"")+(f.cb?"; secure":"")};mt.cookie.get=function(a){return(a=RegExp("(^| )"+a+"=([^;]*)(;|$)").exec(document.cookie))?a[2]:s};mt.p={};mt.p.W=function(a){return document.getElementById(a)};mt.p.va=function(a){var e;for(e="A";(a=a.parentNode)&&1==a.nodeType;)if(a.tagName==e)return a;return s};
(mt.p.R=function(){function a(){if(!a.D){a.D=r;for(var b=0,e=d.length;b<e;b++)d[b]()}}function e(){try{document.documentElement.doScroll("left")}catch(d){setTimeout(e,1);return}a()}var f=w,d=[],b;document.addEventListener?b=function(){document.removeEventListener("DOMContentLoaded",b,w);a()}:document.attachEvent&&(b=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",b),a())});(function(){if(!f)if(f=r,"complete"===document.readyState)a.D=r;else if(document.addEventListener)document.addEventListener("DOMContentLoaded",
b,w),window.addEventListener("load",a,w);else if(document.attachEvent){document.attachEvent("onreadystatechange",b);window.attachEvent("onload",a);var d=w;try{d=window.frameElement==s}catch(m){}document.documentElement.doScroll&&d&&e()}})();return function(b){a.D?b():d.push(b)}}()).D=w;mt.event={};mt.event.c=function(a,e,f){a.attachEvent?a.attachEvent("on"+e,function(d){f.call(a,d)}):a.addEventListener&&a.addEventListener(e,f,w)};
mt.event.preventDefault=function(a){a.preventDefault?a.preventDefault():a.returnValue=w};mt.m={};mt.m.parse=function(){return(new Function('return (" + source + ")'))()};
mt.m.stringify=function(){function a(a){/["\\\x00-\x1f]/.test(a)&&(a=a.replace(/["\\\x00-\x1f]/g,function(a){var d=f[a];if(d)return d;d=a.charCodeAt();return"\\u00"+Math.floor(d/16).toString(16)+(d%16).toString(16)}));return'"'+a+'"'}function e(a){return 10>a?"0"+a:a}var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return function(d){switch(typeof d){case "undefined":return"undefined";case "number":return isFinite(d)?String(d):"null";case "string":return a(d);case "boolean":return String(d);
default:if(d===s)return"null";if(d instanceof Array){var b=["["],f=d.length,m,g,k;for(g=0;g<f;g++)switch(k=d[g],typeof k){case "undefined":case "function":case "unknown":break;default:m&&b.push(","),b.push(mt.m.stringify(k)),m=1}b.push("]");return b.join("")}if(d instanceof Date)return'"'+d.getFullYear()+"-"+e(d.getMonth()+1)+"-"+e(d.getDate())+"T"+e(d.getHours())+":"+e(d.getMinutes())+":"+e(d.getSeconds())+'"';m=["{"];g=mt.m.stringify;for(f in d)if(Object.prototype.hasOwnProperty.call(d,f))switch(k=
d[f],typeof k){case "undefined":case "unknown":case "function":break;default:b&&m.push(","),b=1,m.push(g(f)+":"+g(k))}m.push("}");return m.join("")}}}();mt.lang={};mt.lang.d=function(a,e){return"[object "+e+"]"==={}.toString.call(a)};mt.lang.$a=function(a){return mt.lang.d(a,"Number")&&isFinite(a)};mt.lang.bb=function(a){return mt.lang.d(a,"String")};mt.localStorage={};
mt.localStorage.I=function(){if(!mt.localStorage.g)try{mt.localStorage.g=document.createElement("input"),mt.localStorage.g.type="hidden",mt.localStorage.g.style.display="none",mt.localStorage.g.addBehavior("#default#userData"),document.getElementsByTagName("head")[0].appendChild(mt.localStorage.g)}catch(a){return w}return r};
mt.localStorage.set=function(a,e,f){var d=new Date;d.setTime(d.getTime()+f||31536E6);try{window.localStorage?(e=d.getTime()+"|"+e,window.localStorage.setItem(a,e)):mt.localStorage.I()&&(mt.localStorage.g.expires=d.toUTCString(),mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.setAttribute(a,e),mt.localStorage.g.save(document.location.hostname))}catch(b){}};
mt.localStorage.get=function(a){if(window.localStorage){if(a=window.localStorage.getItem(a)){var e=a.indexOf("|"),f=a.substring(0,e)-0;if(f&&f>(new Date).getTime())return a.substring(e+1)}}else if(mt.localStorage.I())try{return mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.getAttribute(a)}catch(d){}return s};
mt.localStorage.remove=function(a){if(window.localStorage)window.localStorage.removeItem(a);else if(mt.localStorage.I())try{mt.localStorage.g.load(document.location.hostname),mt.localStorage.g.removeAttribute(a),mt.localStorage.g.save(document.location.hostname)}catch(e){}};mt.sessionStorage={};mt.sessionStorage.set=function(a,e){if(window.sessionStorage)try{window.sessionStorage.setItem(a,e)}catch(f){}};
mt.sessionStorage.get=function(a){return window.sessionStorage?window.sessionStorage.getItem(a):s};mt.sessionStorage.remove=function(a){window.sessionStorage&&window.sessionStorage.removeItem(a)};mt.T={};mt.T.log=function(a,e){var f=new Image,d="mini_tangram_log_"+Math.floor(2147483648*Math.random()).toString(36);window[d]=f;f.onload=f.onerror=f.onabort=function(){f.onload=f.onerror=f.onabort=s;f=window[d]=s;e&&e(a)};f.src=a};mt.H={};
mt.H.Da=function(){var a="";if(navigator.plugins&&navigator.mimeTypes.length){var e=navigator.plugins["Shockwave Flash"];e&&e.description&&(a=e.description.replace(/^.*\s+(\S+)\s+\S+$/,"$1"))}else if(window.ActiveXObject)try{if(e=new ActiveXObject("ShockwaveFlash.ShockwaveFlash"))(a=e.GetVariable("$version"))&&(a=a.replace(/^.*\s+(\d+),(\d+).*$/,"$1.$2"))}catch(f){}return a};
mt.H.pa=function(a,e,f,d,b){return'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" id="'+a+'" width="'+f+'" height="'+d+'"><param name="movie" value="'+e+'" /><param name="flashvars" value="'+(b||"")+'" /><param name="allowscriptaccess" value="always" /><embed type="application/x-shockwave-flash" name="'+a+'" width="'+f+'" height="'+d+'" src="'+e+'" flashvars="'+(b||"")+'" allowscriptaccess="always" /></object>'};mt.url={};
mt.url.l=function(a,e){var f=a.match(RegExp("(^|&|\\?|#)("+e+")=([^&#]*)(&|$|#)",""));return f?f[3]:s};mt.url.Za=function(a){return(a=a.match(/^(https?:)\/\//))?a[1]:s};mt.url.za=function(a){return(a=a.match(/^(https?:\/\/)?([^\/\?#]*)/))?a[2].replace(/.*@/,""):s};mt.url.Y=function(a){return(a=mt.url.za(a))?a.replace(/:\d+$/,""):a};mt.url.Ya=function(a){return(a=a.match(/^(https?:\/\/)?[^\/]*(.*)/))?a[2].replace(/[\?#].*/,"").replace(/^$/,"/"):s};
h.k={Ka:"http://tongji.baidu.com/hm-web/welcome/ico",Q:"hm.baidu.com/hm.gif",ha:"baidu.com",Ha:"hmmd",Ia:"hmpl",Ga:"hmkw",Ea:"hmci",Ja:"hmsr",Fa:"hmcu",z:0,o:Math.round(+new Date/1E3),protocol:"https:"===document.location.protocol?"https:":"http:",ab:0,na:6E5,oa:10,U:1024,ma:1,w:2147483647,da:"cc cf ci ck cl cm cp cu cw ds ep et fl ja ln lo lt nv rnd si st su v cv lv api u tt".split(" ")};
(function(){var a={s:{},c:function(a,f){this.s[a]=this.s[a]||[];this.s[a].push(f)},B:function(a,f){this.s[a]=this.s[a]||[];for(var d=this.s[a].length,b=0;b<d;b++)this.s[a][b](f)}};return h.r=a})();
(function(){function a(a,d){var b=document.createElement("script");b.charset="utf-8";e.d(d,"Function")&&(b.readyState?b.onreadystatechange=function(){if("loaded"===b.readyState||"complete"===b.readyState)b.onreadystatechange=s,d()}:b.onload=function(){d()});b.src=a;var l=document.getElementsByTagName("script")[0];l.parentNode.insertBefore(b,l)}var e=mt.lang;return h.load=a})();
(function(){function a(){var a="";h.b.a.nv?(a=encodeURIComponent(document.referrer),window.sessionStorage?f.set("Hm_from_"+c.id,a):e.set("Hm_from_"+c.id,a,864E5)):a=(window.sessionStorage?f.get("Hm_from_"+c.id):e.get("Hm_from_"+c.id))||"";return a}var e=mt.localStorage,f=mt.sessionStorage;return h.V=a})();
(function(){var a=h.k,e=mt.H,f={init:function(){if(""!==c.icon){var d;d=c.icon.split("|");var b=a.Ka+"?s="+c.id,f=("http:"==a.protocol?"http://eiv":"https://bs")+".baidu.com"+d[0]+"."+d[1];switch(d[1]){case "swf":d=e.pa("HolmesIcon"+a.o,f,d[2],d[3],"s="+b);break;case "gif":d='<a href="'+b+'" target="_blank"><img border="0" src="'+f+'" width="'+d[2]+'" height="'+d[3]+'"></a>';break;default:d='<a href="'+b+'" target="_blank">'+d[0]+"</a>"}document.write(d)}}};h.r.c("pv-b",f.init);return f})();
(function(){var a=mt.p,e=mt.event,f=mt.j,d=h.k,b=[],l={ea:function(){c.ctrk&&(e.c(document,"mouseup",l.la()),e.c(window,"unload",function(){l.F()}),setInterval(function(){l.F()},d.na))},la:function(){return function(a){a=l.wa(a);if(""!==a){var e=(d.protocol+"//"+d.Q+"?"+h.b.ca().replace(/ep=[^&]*/,"ep="+encodeURIComponent("["+a+"]"))).length;e+(d.w+"").length>d.U||(e+encodeURIComponent(b.join(",")+(b.length?",":"")).length+(d.w+"").length>d.U&&l.F(),b.push(a),(b.length>=d.oa||/t:a/.test(a))&&l.F())}}},
wa:function(b){if(0===d.ma){var e=b.target||b.srcElement,k=e.tagName.toLowerCase();if("embed"==k||"object"==k)return""}f.N?(e=Math.max(document.documentElement.scrollTop,document.body.scrollTop),k=Math.max(document.documentElement.scrollLeft,document.body.scrollLeft),k=b.clientX+k,e=b.clientY+e):(k=b.pageX,e=b.pageY);var n=window.innerWidth||document.documentElement.clientWidth||document.body.offsetWidth;switch(c.align){case 1:k-=n/2;break;case 2:k-=n}k="{x:"+k+",y:"+e+",";e=b.target||b.srcElement;
return k=(b="a"==e.tagName.toLowerCase()?e:a.va(e))?k+("t:a,u:"+encodeURIComponent(b.href)+"}"):k+"t:b}"},F:function(){0!==b.length&&(h.b.a.et=2,h.b.a.ep="["+b.join(",")+"]",h.b.i(),b=[])}};h.r.c("pv-b",l.ea);return l})();
(function(){var a=mt.p,e=h.k,f=h.load,d=h.V;h.r.c("pv-b",function(){c.rec&&a.R(function(){for(var b=0,l=c.rp.length;b<l;b++){var m=c.rp[b][0],g=c.rp[b][1],k=a.W("hm_t_"+m);if(g&&!(2==g&&!k||k&&""!==k.innerHTML))k="",k=Math.round(Math.random()*e.w),k=4==g?"http://crs.baidu.com/hl.js?"+["siteId="+c.id,"planId="+m,"rnd="+k].join("&"):"http://crs.baidu.com/t.js?"+["siteId="+c.id,"planId="+m,"from="+d(),"referer="+encodeURIComponent(document.referrer),"title="+encodeURIComponent(document.title),"rnd="+
k].join("&"),f(k)}})})})();(function(){var a=h.k,e=h.load,f=h.V;h.r.c("pv-b",function(){if(c.trust&&c.vcard){var d=a.protocol+"//trust.baidu.com/vcard/v.js?"+["siteid="+c.vcard,"url="+encodeURIComponent(document.location.href),"source="+f(),"rnd="+Math.round(Math.random()*a.w),"hm=1"].join("&");e(d)}})})();
(function(){function a(){return function(){h.b.a.nv=0;h.b.a.st=4;h.b.a.et=3;h.b.a.ep=h.J.Ba()+","+h.J.ya();h.b.i()}}function e(){clearTimeout(B);var a;z&&(a="visible"==document[z]);C&&(a=!document[C]);g="undefined"==typeof a?r:a;if((!m||!k)&&g&&n)u=r,p=+new Date;else if(m&&k&&(!g||!n))u=w,t+=+new Date-p;m=g;k=n;B=setTimeout(e,100)}function f(a){var k=document,p="";if(a in k)p=a;else for(var b=["webkit","ms","moz","o"],d=0;d<b.length;d++){var e=b[d]+a.charAt(0).toUpperCase()+a.slice(1);if(e in k){p=
e;break}}return p}function d(a){if(!("focus"==a.type||"blur"==a.type)||!(a.target&&a.target!=window))n="focus"==a.type||"focusin"==a.type?r:w,e()}var b=mt.event,l=h.r,m=r,g=r,k=r,n=r,v=+new Date,p=v,t=0,u=r,z=f("visibilityState"),C=f("hidden"),B;e();(function(){var a=z.replace(/[vV]isibilityState/,"visibilitychange");b.c(document,a,e);b.c(window,"pageshow",e);b.c(window,"pagehide",e);"object"==typeof document.onfocusin?(b.c(document,"focusin",d),b.c(document,"focusout",d)):(b.c(window,"focus",d),
b.c(window,"blur",d))})();h.J={Ba:function(){return+new Date-v},ya:function(){return u?+new Date-p+t:t}};l.c("pv-b",function(){b.c(window,"unload",a())});return h.J})();
(function(){var a=mt.lang,e=h.k,f=h.load,d={Ma:function(b){if((window._dxt===q||a.d(window._dxt,"Array"))&&"undefined"!==typeof h.b){var d=h.b.L();f([e.protocol,"//datax.baidu.com/x.js?si=",c.id,"&dm=",encodeURIComponent(d)].join(""),b)}},Wa:function(b){if(a.d(b,"String")||a.d(b,"Number"))window._dxt=window._dxt||[],window._dxt.push(["_setUserId",b])}};return h.qa=d})();
(function(){function a(k){for(var b in k)if({}.hasOwnProperty.call(k,b)){var d=k[b];f.d(d,"Object")||f.d(d,"Array")?a(d):k[b]=String(d)}}function e(a){return a.replace?a.replace(/'/g,"'0").replace(/\*/g,"'1").replace(/!/g,"'2"):a}var f=mt.lang,d=mt.m,b=h.k,l=h.r,m=h.qa,g={A:[],G:0,aa:w,init:function(){g.e=0;l.c("pv-b",function(){g.ra();g.ta()});l.c("pv-d",g.ua);l.c("stag-b",function(){h.b.a.api=g.e||g.G?g.e+"_"+g.G:""});l.c("stag-d",function(){h.b.a.api=0;g.e=0;g.G=0})},ra:function(){var a=window._hmt||
[];if(!a||f.d(a,"Array"))window._hmt={id:c.id,cmd:{},push:function(){for(var a=window._hmt,k=0;k<arguments.length;k++){var p=arguments[k];f.d(p,"Array")&&(a.cmd[a.id].push(p),"_setAccount"===p[0]&&(1<p.length&&/^[0-9a-f]{32}$/.test(p[1]))&&(p=p[1],a.id=p,a.cmd[p]=a.cmd[p]||[]))}}},window._hmt.cmd[c.id]=[],window._hmt.push.apply(window._hmt,a)},ta:function(){var a=window._hmt;if(a&&a.cmd&&a.cmd[c.id])for(var b=a.cmd[c.id],d=/^_track(Event|MobConv|Order|RTEvent)$/,p=0,e=b.length;p<e;p++){var f=b[p];
d.test(f[0])?g.A.push(f):g.P(f)}a.cmd[c.id]={push:g.P}},ua:function(){if(0<g.A.length)for(var a=0,b=g.A.length;a<b;a++)g.P(g.A[a]);g.A=s},P:function(a){var b=a[0];if(g.hasOwnProperty(b)&&f.d(g[b],"Function"))g[b](a)},_setAccount:function(a){1<a.length&&/^[0-9a-f]{32}$/.test(a[1])&&(g.e|=1)},_setAutoPageview:function(a){if(1<a.length&&(a=a[1],w===a||r===a))g.e|=2,h.b.Z=a},_trackPageview:function(a){if(1<a.length&&a[1].charAt&&"/"===a[1].charAt(0)){g.e|=4;h.b.a.et=0;h.b.a.ep="";h.b.M?(h.b.a.nv=0,h.b.a.st=
4):h.b.M=r;var d=h.b.a.u,e=h.b.a.su;h.b.a.u=b.protocol+"//"+document.location.host+a[1];g.aa||(h.b.a.su=document.location.href);h.b.i();h.b.a.u=d;h.b.a.su=e}},_trackEvent:function(a){2<a.length&&(g.e|=8,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=4,h.b.a.ep=e(a[1])+"*"+e(a[2])+(a[3]?"*"+e(a[3]):"")+(a[4]?"*"+e(a[4]):""),h.b.i())},_setCustomVar:function(a){if(!(4>a.length)){var b=a[1],d=a[4]||3;if(0<b&&6>b&&0<d&&4>d){g.G++;for(var p=(h.b.a.cv||"*").split("!"),f=p.length;f<b-1;f++)p.push("*");p[b-1]=d+"*"+e(a[2])+
"*"+e(a[3]);h.b.a.cv=p.join("!");a=h.b.a.cv.replace(/[^1](\*[^!]*){2}/g,"*").replace(/((^|!)\*)+$/g,"");""!==a?h.b.setData("Hm_cv_"+c.id,encodeURIComponent(a),c.age):h.b.Pa("Hm_cv_"+c.id)}}},_setReferrerOverride:function(a){1<a.length&&(h.b.a.su=a[1].charAt&&"/"===a[1].charAt(0)?b.protocol+"//"+window.location.host+a[1]:a[1],g.aa=r)},_trackOrder:function(b){b=b[1];f.d(b,"Object")&&(a(b),g.e|=16,h.b.a.nv=0,h.b.a.st=4,h.b.a.et=94,h.b.a.ep=d.stringify(b),h.b.i())},_trackMobConv:function(a){if(a={webim:1,
tel:2,map:3,sms:4,callback:5,share:6}[a[1]])g.e|=32,h.b.a.et=93,h.b.a.ep=a,h.b.i()},_trackRTPageview:function(b){b=b[1];f.d(b,"Object")&&(a(b),b=d.stringify(b),512>=encodeURIComponent(b).length&&(g.e|=64,h.b.a.rt=b))},_trackRTEvent:function(e){e=e[1];if(f.d(e,"Object")){a(e);e=encodeURIComponent(d.stringify(e));var l=function(a){var b=h.b.a.rt;g.e|=128;h.b.a.et=90;h.b.a.rt=a;h.b.i();h.b.a.rt=b},m=e.length;if(900>=m)l.call(this,e);else for(var m=Math.ceil(m/900),p="block|"+Math.round(Math.random()*
b.w).toString(16)+"|"+m+"|",t=[],u=0;u<m;u++)t.push(u),t.push(e.substring(900*u,900*u+900)),l.call(this,p+t.join("|")),t=[]}},_setUserId:function(a){a=a[1];m.Ma();m.Wa(a)}};g.init();h.ia=g;return h.ia})();
(function(){function a(){"undefined"===typeof window["_bdhm_loaded_"+c.id]&&(window["_bdhm_loaded_"+c.id]=r,this.a={},this.Z=r,this.M=w,this.init())}var e=mt.url,f=mt.T,d=mt.H,b=mt.lang,l=mt.cookie,m=mt.j,g=mt.localStorage,k=mt.sessionStorage,n=h.k,v=h.r;a.prototype={O:function(a,b){a="."+a.replace(/:\d+/,"");b="."+b.replace(/:\d+/,"");var d=a.indexOf(b);return-1<d&&d+b.length===a.length},ba:function(a,b){a=a.replace(/^https?:\/\//,"");return 0===a.indexOf(b)},C:function(a){for(var b=0;b<c.dm.length;b++)if(-1<
c.dm[b].indexOf("/")){if(this.ba(a,c.dm[b]))return r}else{var d=e.Y(a);if(d&&this.O(d,c.dm[b]))return r}return w},L:function(){for(var a=document.location.hostname,b=0,d=c.dm.length;b<d;b++)if(this.O(a,c.dm[b]))return c.dm[b].replace(/(:\d+)?[\/\?#].*/,"");return a},X:function(){for(var a=0,b=c.dm.length;a<b;a++){var d=c.dm[a];if(-1<d.indexOf("/")&&this.ba(document.location.href,d))return d.replace(/^[^\/]+(\/.*)/,"$1")+"/"}return"/"},Ca:function(){if(!document.referrer)return n.o-n.z>c.vdur?1:4;
var a=w;this.C(document.referrer)&&this.C(document.location.href)?a=r:(a=e.Y(document.referrer),a=this.O(a||"",document.location.hostname));return a?n.o-n.z>c.vdur?1:4:3},getData:function(a){try{return l.get(a)||k.get(a)||g.get(a)}catch(b){}},setData:function(a,b,d){try{l.set(a,b,{domain:this.L(),path:this.X(),K:d}),d?g.set(a,b,d):k.set(a,b)}catch(e){}},Pa:function(a){try{l.set(a,"",{domain:this.L(),path:this.X(),K:-1}),k.remove(a),g.remove(a)}catch(b){}},Ua:function(){var a,b,d,e,f;n.z=this.getData("Hm_lpvt_"+
c.id)||0;13===n.z.length&&(n.z=Math.round(n.z/1E3));b=this.Ca();a=4!==b?1:0;if(d=this.getData("Hm_lvt_"+c.id)){e=d.split(",");for(f=e.length-1;0<=f;f--)13===e[f].length&&(e[f]=""+Math.round(e[f]/1E3));for(;2592E3<n.o-e[0];)e.shift();f=4>e.length?2:3;for(1===a&&e.push(n.o);4<e.length;)e.shift();d=e.join(",");e=e[e.length-1]}else d=n.o,e="",f=1;this.setData("Hm_lvt_"+c.id,d,c.age);this.setData("Hm_lpvt_"+c.id,n.o);d=n.o===this.getData("Hm_lpvt_"+c.id)?"1":"0";if(0===c.nv&&this.C(document.location.href)&&
(""===document.referrer||this.C(document.referrer)))a=0,b=4;this.a.nv=a;this.a.st=b;this.a.cc=d;this.a.lt=e;this.a.lv=f},ca:function(){for(var a=[],b=this.a.et,d=0,e=n.da.length;d<e;d++){var f=n.da[d],g=this.a[f];"undefined"!==typeof g&&""!==g&&("tt"!==f||"tt"===f&&0===b)&&a.push(f+"="+encodeURIComponent(g))}this.a.rt&&(0===b?a.push("rt="+encodeURIComponent(this.a.rt)):90===b&&a.push("rt="+this.a.rt));return a.join("&")},Va:function(){this.Ua();this.a.si=c.id;this.a.su=document.referrer;this.a.ds=
m.Qa;this.a.cl=m.colorDepth+"-bit";this.a.ln=m.language;this.a.ja=m.javaEnabled?1:0;this.a.ck=m.cookieEnabled?1:0;this.a.lo="number"===typeof _bdhm_top?1:0;this.a.fl=d.Da();this.a.v="1.1.27";this.a.cv=decodeURIComponent(this.getData("Hm_cv_"+c.id)||"");this.a.tt=document.title||"";var a=document.location.href;this.a.cm=e.l(a,n.Ha)||"";this.a.cp=e.l(a,n.Ia)||"";this.a.cw=e.l(a,n.Ga)||"";this.a.ci=e.l(a,n.Ea)||"";this.a.cf=e.l(a,n.Ja)||"";this.a.cu=e.l(a,n.Fa)||""},init:function(){try{this.Va(),0===
this.a.nv?this.Sa():this.S(".*"),h.b=this,this.ka(),v.B("pv-b"),this.Ra()}catch(a){var b=[];b.push("si="+c.id);b.push("n="+encodeURIComponent(a.name));b.push("m="+encodeURIComponent(a.message));b.push("r="+encodeURIComponent(document.referrer));f.log(n.protocol+"//"+n.Q+"?"+b.join("&"))}},Ra:function(){function a(){v.B("pv-d")}this.Z?(this.M=r,this.a.et=0,this.a.ep="",this.i(a)):a()},i:function(a){var d=this;d.a.rnd=Math.round(Math.random()*n.w);v.B("stag-b");var e=n.protocol+"//"+n.Q+"?"+d.ca();
v.B("stag-d");d.ga(e);f.log(e,function(e){d.S(e);b.d(a,"Function")&&a.call(d)})},ka:function(){var a=document.location.hash.substring(1),b=RegExp(c.id),d=-1<document.referrer.indexOf(n.ha),f=e.l(a,"jn"),g=/^heatlink$|^select$/.test(f);a&&(b.test(a)&&d&&g)&&(this.a.rnd=Math.round(Math.random()*n.w),a=document.createElement("script"),a.setAttribute("type","text/javascript"),a.setAttribute("charset","utf-8"),a.setAttribute("src",n.protocol+"//"+c.js+f+".js?"+this.a.rnd),f=document.getElementsByTagName("script")[0],
f.parentNode.insertBefore(a,f))},ga:function(a){var b=k.get("Hm_unsent_"+c.id)||"",d=this.a.u?"":"&u="+encodeURIComponent(document.location.href),b=encodeURIComponent(a.replace(/^https?:\/\//,"")+d)+(b?","+b:"");k.set("Hm_unsent_"+c.id,b)},S:function(a){var b=k.get("Hm_unsent_"+c.id)||"";b&&(a=encodeURIComponent(a.replace(/^https?:\/\//,"")),a=RegExp(a.replace(/([\*\(\)])/g,"\\$1")+"(%26u%3D[^,]*)?,?","g"),(b=b.replace(a,"").replace(/,$/,""))?k.set("Hm_unsent_"+c.id,b):k.remove("Hm_unsent_"+c.id))},
Sa:function(){var a=this,b=k.get("Hm_unsent_"+c.id);if(b)for(var b=b.split(","),d=function(b){f.log(n.protocol+"//"+decodeURIComponent(b),function(b){a.S(b)})},e=0,g=b.length;e<g;e++)d(b[e])}};return new a})();var x=h.k,y=h.load;if(c.apps){var A=[x.protocol,"//ers.baidu.com/app/s.js?"];A.push(c.apps);y(A.join(""))}var D=h.k,E=h.load;if(c.conv&&"http:"===D.protocol){var F=["http://page.baidu.com/conversion_js.php?sid="];F.push(c.conv);E(F.join(""))}var G=h.k,H=h.load;
c.lxb&&H([G.protocol,"//lxbjs.baidu.com/lxb.js?sid=",c.lxb].join(""));var I=h.load,J=h.k.protocol;if(c.qiao){for(var K=[J+"//goutong.baidu.com/site/"],L=c.id,M=5381,N=L.length,O=0;O<N;O++)M=(33*M+Number(L.charCodeAt(O)))%4294967296;2147483648<M&&(M-=2147483648);K.push(M%1E3+"/");K.push(c.id+"/b.js");K.push("?siteId="+c.qiao);I(K.join(""))}
(function(){var a=mt.p,e=mt.event,f=mt.url,d=mt.m;try{if(window.performance&&performance.timing&&"undefined"!==typeof h.b){var b=+new Date,l=function(a){var b=performance.timing,d=b[a+"Start"]?b[a+"Start"]:0;a=b[a+"End"]?b[a+"End"]:0;return{start:d,end:a,value:0<a-d?a-d:0}},m=s;a.R(function(){m=+new Date});var g=function(){var a,e,g;g=l("navigation");e=l("request");g={netAll:e.start-g.start,netDns:l("domainLookup").value,netTcp:l("connect").value,srv:l("response").start-e.start,dom:performance.timing.domInteractive-
performance.timing.fetchStart,loadEvent:l("loadEvent").end-g.start};a=document.referrer;var k=a.match(/^(http[s]?:\/\/)?([^\/]+)(.*)/)||[],u=s;e=s;if("www.baidu.com"===k[2]||"m.baidu.com"===k[2])u=f.l(a,"qid"),e=f.l(a,"click_t");a=u;g.qid=a!=s?a:"";e!=s?(g.bdDom=m?m-e:0,g.bdRun=b-e,g.bdDef=l("navigation").start-e):(g.bdDom=0,g.bdRun=0,g.bdDef=0);h.b.a.et=87;h.b.a.ep=d.stringify(g);h.b.i()};e.c(window,"load",function(){setTimeout(g,500)})}}catch(k){}})();
(function(){var a=mt.j,e=mt.lang,f=mt.event,d=mt.m;if("undefined"!==typeof h.b&&(c.med||(!a.N||7<a.La)&&c.cvcc)){var b,l,m,g,k=function(a){if(a.item){for(var b=a.length,d=Array(b);b--;)d[b]=a[b];return d}return[].slice.call(a)},n=function(a,b){for(var d in a)if(a.hasOwnProperty(d)&&b.call(a,d,a[d])===w)return w},v=function(a,f){var g={};g.n=b;g.t="clk";g.v=a;if(f){var k=f.getAttribute("href"),l=f.getAttribute("onclick")?""+f.getAttribute("onclick"):s,n=f.getAttribute("id")||"";m.test(k)?(g.sn="mediate",
g.snv=k):e.d(l,"String")&&m.test(l)&&(g.sn="wrap",g.snv=l);g.id=n}h.b.a.et=86;h.b.a.ep=d.stringify(g);h.b.i();for(g=+new Date;400>=+new Date-g;);};if(c.med)l="/zoosnet",b="swt",m=/swt|zixun|call|chat|zoos|business|talk|kefu|openkf|online|\/LR\/Chatpre\.aspx/i,g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f=0,g=b.length;f<g;f++)d=b[f],e=d.getAttribute("onclick"),
d=d.getAttribute("href"),(m.test(e)||m.test(d))&&a.push(b[f]);return a}};else if(c.cvcc){l="/other-comm";b="other";m=c.cvcc.q||q;var p=c.cvcc.id||q;g={click:function(){for(var a=[],b=k(document.getElementsByTagName("a")),b=[].concat.apply(b,k(document.getElementsByTagName("area"))),b=[].concat.apply(b,k(document.getElementsByTagName("img"))),d,e,f,g=0,l=b.length;g<l;g++)d=b[g],m!==q?(e=d.getAttribute("onclick"),f=d.getAttribute("href"),p?(d=d.getAttribute("id"),(m.test(e)||m.test(f)||p.test(d))&&
a.push(b[g])):(m.test(e)||m.test(f))&&a.push(b[g])):p!==q&&(d=d.getAttribute("id"),p.test(d)&&a.push(b[g]));return a}}}if("undefined"!==typeof g&&"undefined"!==typeof m){var t;l+=/\/$/.test(l)?"":"/";var u=function(a,b){if(t===b)return v(l+a,b),w;if(e.d(b,"Array")||e.d(b,"NodeList"))for(var d=0,f=b.length;d<f;d++)if(t===b[d])return v(l+a+"/"+(d+1),b[d]),w};f.c(document,"mousedown",function(a){a=a||window.event;t=a.target||a.srcElement;var b={};for(n(g,function(a,d){b[a]=e.d(d,"Function")?d():document.getElementById(d)});t&&
t!==document&&n(b,u)!==w;)t=t.parentNode})}}})();(function(){var a=mt.p,e=mt.lang,f=mt.event,d=mt.m;if("undefined"!==typeof h.b&&e.d(c.cvcf,"Array")&&0<c.cvcf.length){var b={fa:function(){for(var d=c.cvcf.length,e,g=0;g<d;g++)(e=a.W(decodeURIComponent(c.cvcf[g])))&&f.c(e,"click",b.sa())},sa:function(){return function(){h.b.a.et=86;var a={n:"form",t:"clk"};a.id=this.id;h.b.a.ep=d.stringify(a);h.b.i()}}};a.R(function(){b.fa()})}})();
(function(){var a=mt.event,e=mt.m;if(c.med&&"undefined"!==typeof h.b){var f=+new Date,d={n:"anti",sb:0,kb:0,clk:0},b=function(){h.b.a.et=86;h.b.a.ep=e.stringify(d);h.b.i()};a.c(document,"click",function(){d.clk++});a.c(document,"keyup",function(){d.kb=1});a.c(window,"scroll",function(){d.sb++});a.c(window,"unload",function(){d.t=+new Date-f;b()});a.c(window,"load",function(){setTimeout(b,5E3)})}})();
(function(){function a(){this.f=s}var e=mt.T,f=mt.j;a.prototype={Na:function(a){if(this.f)this.h(a,0);else if(this.isSupported()){try{this.f=new ActiveXObject("BDEXIE.BDExExtension.1"),this.$=r}catch(d){this.$=w}this.$?this.h(a,0):this.h(a,-1)}else this.h(a,-1)},Xa:function(){this.f&&delete this.f;this.f=s},Ta:function(a,d,e){if(this.f&&"SetLocalCache"in this.f)try{this.f.SetLocalCache(a,d)===q&&this.h(e,0)}catch(f){this.h(e,-1)}else this.h(e,-1)},Aa:function(a,d){if(this.f&&"GetLocalCache"in this.f)try{this.h(d,
this.f.GetLocalCache(a))}catch(e){this.h(d,"")}else this.h(d,"")},xa:function(a){if(this.f&&"GetCryptStr"in this.f)try{this.h(a,this.f.GetCryptStr("strEncryptID1"))}catch(d){this.h(a,"")}else this.h(a,"")},h:function(a,d){"function"===typeof a&&a(d,this)},isSupported:function(){if(window.ActiveXObject||"ActiveXObject"in window)try{return!!new ActiveXObject("BDEXIE.BDExExtension.1")}catch(a){}return w},Oa:function(){var a=this;this.xa(function(d){d!==q&&""!==d&&(e.log("//datax.baidu.com/x.gif?dm="+
encodeURIComponent("datax.baidu.com/webadapter/guid")+"&ac="+encodeURIComponent(d)+"&v=hm-webadapter-0.0.1&rnd="+Math.round(2147483647*Math.random())),a.Ta("hmKey",+new Date,function(){a.Xa()}))})}};if(f.N&&/^http(s)?:$/.test(document.location.protocol)){var d=new a;d.Na(function(a){0===a&&d.Aa("hmKey",function(a){a=+a;(isNaN(a)||6048E5<+new Date-a)&&d.Oa()})})}})();})();
